/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignIdRouteImport } from './routes/campaign.$id'
import { Route as CampaignNewRouteImport } from './routes/campaign.new'
import { Route as CampaignIdApplyRouteImport } from './routes/campaign.$id.apply'
import { Route as CampaignIdEditRouteImport } from './routes/campaign_.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIdRoute = CampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignNewRoute = CampaignNewRouteImport.update({
  id: '/campaign/new',
  path: '/campaign/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIdApplyRoute = CampaignIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CampaignIdRoute,
} as any)
const CampaignIdEditRoute = CampaignIdEditRouteImport.update({
  id: '/campaign_/$id/edit',
  path: '/campaign/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign/$id': typeof CampaignIdRouteWithChildren
  '/campaign/new': typeof CampaignNewRoute
  '/campaign/$id/apply': typeof CampaignIdApplyRoute
  '/campaign/$id/edit': typeof CampaignIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign/$id': typeof CampaignIdRouteWithChildren
  '/campaign/new': typeof CampaignNewRoute
  '/campaign/$id/apply': typeof CampaignIdApplyRoute
  '/campaign/$id/edit': typeof CampaignIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign/$id': typeof CampaignIdRouteWithChildren
  '/campaign/new': typeof CampaignNewRoute
  '/campaign/$id/apply': typeof CampaignIdApplyRoute
  '/campaign_/$id/edit': typeof CampaignIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign/$id'
    | '/campaign/new'
    | '/campaign/$id/apply'
    | '/campaign/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign/$id'
    | '/campaign/new'
    | '/campaign/$id/apply'
    | '/campaign/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/campaign/$id'
    | '/campaign/new'
    | '/campaign/$id/apply'
    | '/campaign_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignIdRoute: typeof CampaignIdRouteWithChildren
  CampaignNewRoute: typeof CampaignNewRoute
  CampaignIdEditRoute: typeof CampaignIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$id': {
      id: '/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof CampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/new': {
      id: '/campaign/new'
      path: '/campaign/new'
      fullPath: '/campaign/new'
      preLoaderRoute: typeof CampaignNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$id/apply': {
      id: '/campaign/$id/apply'
      path: '/apply'
      fullPath: '/campaign/$id/apply'
      preLoaderRoute: typeof CampaignIdApplyRouteImport
      parentRoute: typeof CampaignIdRoute
    }
    '/campaign_/$id/edit': {
      id: '/campaign_/$id/edit'
      path: '/campaign/$id/edit'
      fullPath: '/campaign/$id/edit'
      preLoaderRoute: typeof CampaignIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CampaignIdRouteChildren {
  CampaignIdApplyRoute: typeof CampaignIdApplyRoute
}

const CampaignIdRouteChildren: CampaignIdRouteChildren = {
  CampaignIdApplyRoute: CampaignIdApplyRoute,
}

const CampaignIdRouteWithChildren = CampaignIdRoute._addFileChildren(
  CampaignIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignIdRoute: CampaignIdRouteWithChildren,
  CampaignNewRoute: CampaignNewRoute,
  CampaignIdEditRoute: CampaignIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
